first try
redpandageddon/mmadpractice pull request #1
Opened 2020-09-30 18:23 UTC by redpandageddon

rdy 4 review

2020-10-26 18:14 UTC, aqaqaqaqaq requested changes

2020-10-26 18:14 UTC, aqaqaqaqaq commented on pr02.py
> +    B = np.zeros((arrayAmount, 1))
дать массивам A и B осмысленные названия

2020-10-26 18:14 UTC, aqaqaqaqaq commented on pr02.py
> +    result = math.sqrt(sum(asd))
может переименовать как промежуточное действе номер 1 и т.д.?

2020-10-26 19:03 UTC, redpandageddon commented on pr02.py
> +    result = math.sqrt(sum(asd))
No

2020-10-31 12:30 UTC, stanislavlyalin commented on pr02.py
> +def AbsArrayDifference(A, B):
Если A и B являются numpy array (а их можно к таковым привести), вычисление модуля разностей может быть выполнено в одну строку кода. И желательно также проверять, что размеры массивов совпадают, иначе, например, кидать исключение.

2020-10-31 12:30 UTC, stanislavlyalin commented on pr02.py
> +def BestArray(arrayAmount, itemAmmount):
Название не подходящее. Лучший массив по какому критерию?

2020-10-31 12:30 UTC, stanislavlyalin commented on pr02.py
> +        arrays[i] = 10 * np.random.random(itemAmmount) - 5
В одном цикле происходит и генерация матрицы, и вычисление сумм по строкам. Это разные логические действия, и лучше их разделить: отдельно генерация матрицы, отдельно поиск строки с максимальной суммой элементов. Суммирование по строкам можно выполнить с помощью `np.sum`, задав нужное значение параметра `axis`.

2020-10-31 12:30 UTC, stanislavlyalin commented on pr02.py
> +    result = math.sqrt(sum(diff.ravel()))
Можно сразу сделать `return math.sqrt(sum(diff.ravel()))`
math, кстати, можно не импортировать, а воспользоваться функцией sqrt из np

2020-11-14 15:23 UTC, merged