first try
redpandageddon/mmadpractice pull request #2
Opened 2020-10-03 19:13 UTC by redpandageddon

04 done

2020-10-26 18:21 UTC, aqaqaqaqaq commented on 04/k_means.py
> +  # Поэкспериментируйте в консоли Python с функциями all и any, чтобы понять, как они работают.
или удалить или писать каждый блок кода после каждого задания чтобы понятно было

2020-10-26 18:27 UTC, aqaqaqaqaq commented on 04/k_means.py
> +    return centers
в цикле есть условие, и лучше писать туда а не в брейк, так гораздо проще понять тому кто пытается разобраться

2020-10-26 18:28 UTC, aqaqaqaqaq requested changes
Надо переписать цикл

2020-10-31 12:33 UTC, stanislavlyalin commented on 04/k_means.py
> +def dist(A, B, N):
В первой практике вы уже реализовывали функцию вычисления евклидова расстояния. Используйте её. Код здесь слишком громоздкий.

2020-10-31 12:33 UTC, stanislavlyalin commented on 04/k_means.py
> +def curse(k,X):
Код ниже, практически один в один, сдавала мне предыдущая группа. Необходимо сделать самостоятельно.

2020-10-31 12:51 UTC, redpandageddon commented on 04/k_means.py
> +def curse(k,X):
Если я не ошибаюсь, все исходные commitы нашей группы были раньше, что явно указывает на то, что вероятность, того, что мы `заимствовали` их код крайне мала.

2020-11-14 15:27 UTC, merged