pract 06
redpandageddon/mmadpractice pull request #4
Opened 2020-10-03 19:19 UTC by redpandageddon

done

2020-10-26 18:39 UTC, aqaqaqaqaq commented on 06/1paramlinearregression.py
> +asd = predict(test, theta)
поменять название переменной

2020-10-26 18:42 UTC, aqaqaqaqaq commented on 06/2paramslinearregression.py
> +asd1 = compute_cost(X_ones, y, theta)
ещё раз

2020-10-26 18:42 UTC, aqaqaqaqaq commented on 06/2paramslinearregression.py
> +asd2 = compute_cost(X_ones, y, theta)
ещё раз

2020-10-26 18:43 UTC, aqaqaqaqaq commented on 06/rss.py
> +asd = compute_cost(X, y, c)
...

2020-10-26 18:44 UTC, aqaqaqaqaq requested changes
ну вроде норм но нажму Request changes прост на всякий случай

2020-10-27 09:19 UTC, redpandageddon commented
Done

2020-11-01 11:44 UTC, stanislavlyalin commented on 06/2paramslinearregression.py
> +normalize(square)
Возвращаемое значение не используется, а модифицируется исходный массив. Тогда оператор `return` в `normalize` можно убрать

2020-11-01 11:44 UTC, stanislavlyalin commented on 06/2paramslinearregression.py
> +def compute_cost(X, y, theta):
Не нужно вводить дополнительные реализации `compute_cost` и `gradient_descent` для регрессии с несколькими входными параметрами. Реализация должна быть универсальная и работать с любым количеством входных параметров.

2020-11-01 11:44 UTC, stanislavlyalin commented on 06/1paramlinearregression.py
> +  plt.plot(np.arange(500), J_theta, 'k-')
Не нужно выводить график прямо в функции `gradient_descent`. Если хочется посмотреть график, можно заполнить значениями массив, вернуть его из функции и затем отобразить.

2020-11-01 11:44 UTC, stanislavlyalin commented on 06/1paramlinearregression.py
> +  theta = np.ones((n, 1))
Массив `theta` объявляется, но нигде не используется, кроме присваивания `tmp` один раз. Алгоритм должен работать так: вычисляем cost с текущими `theta`, в цикле меняем `tmp`, а после цикла, когда все j-е значения коэффициентов посчитаны, присваиваем `theta = tmp`. У вас реализовано не правильно: при вычислении `cost` используются коэффициенты `tmp`, которые меняются в этом же цикле.

2020-11-01 11:44 UTC, stanislavlyalin commented on 06/1paramlinearregression.py
> +  J_theta = np.zeros((iterations, 1))
Зачем делать вектор-столбец? Почему не достаточно обычного массива (np.array или list)?

2020-11-01 11:44 UTC, stanislavlyalin commented on 06/1paramlinearregression.py
> +      k = (alpha / m)
`alpha` и `m` в цикле не меняются, поэтому значение `k` можно вычислить один раз перед циклом

2020-11-01 11:44 UTC, stanislavlyalin commented on 06/2paramslinearregression.py
> +def predict(X, theta):
Используйте объявленную выше функцию. Если она используется в нескольких модулях, вынесите её в отдельный файл и подключайте из этого файла.

2020-11-01 11:44 UTC, stanislavlyalin commented on 06/2paramslinearregression.py
> +  plt.plot(np.arange(1000), J_theta, 'k-')
Почему `1000`, а не `iterations`?

2020-11-01 11:44 UTC, stanislavlyalin commented on 06/2paramslinearregression.py
> +print('prediction ->' + str(predict(test, theta)))
Не хватает комментариев к коду. Какое задание из методички реализует каждый из фрагментов кода?

2020-11-01 11:44 UTC, stanislavlyalin commented on 06/rss.py
> +def predict(X, theta):
Снова дублирование функций `compute_cost` и `predict`. Необходимо вынести реализацию в отдельный файл

2020-11-02 10:25 UTC, redpandageddon commented on 06/1paramlinearregression.py
> +  J_theta = np.zeros((iterations, 1))
по указаниям:   # создать вектор-столбец theta и инициализировать его первый элемент нулем, а остальные элементы единицами. Количество элементов в theta равно n.
  # создать вектор-столбец J_theta, размер которого равен количеству итераций, заполненный нулями

2020-11-18 19:01 UTC, merged