Add files via upload
redpandageddon/mmadpractice pull request #7
Opened 2020-11-22 16:32 UTC by f-v-a

2020-11-22 16:38 UTC, redpandageddon commented on 07/predict.py
> +    return res
Можно написать в одну строчку

2020-11-22 16:48 UTC, redpandageddon requested changes
Убрать из репозитория файлы с расширением .mat

2020-11-22 16:48 UTC, redpandageddon commented on 07/predict.py
> +    return res
Возвращать сразу вычисленное значение, не создавая отдельной переменной

2020-11-22 16:48 UTC, redpandageddon commented on 07/run.py
> +print(q)
В принципе, бесполезное действие

2020-11-22 16:48 UTC, redpandageddon commented on 07/run.py
> +rp = np.random.permutation(m)
Дублирование кода с 16 строки. Сделать отдельную функцию

2020-11-22 16:48 UTC, redpandageddon commented on 07/run.py
> +qwerty = np.zeros((100,x_axis.shape[1]))
Из названия переменной не понятно что в ней

2020-11-23 16:24 UTC, stanislavlyalin commented on 07/run.py
> +    x[i] = x_axis[indexes[i]]
Попробуйте строки 20-24 упростить, используя функцию [choice](https://docs.scipy.org/doc//numpy-1.10.4/reference/generated/numpy.random.choice.html)

2020-11-23 16:24 UTC, stanislavlyalin commented on 07/run.py
> +y_axis = np.int64(test_set['y'])
Обычно называют `X_test` и `y_test`. Читающим проще будет понять код

2020-11-23 16:24 UTC, stanislavlyalin commented on 07/run.py
> +q = (pre == y_axis.ravel())
Имя `q` ни о чём не говорит. Можно в данном случае вообще не создавать переменную

2020-11-23 16:24 UTC, stanislavlyalin commented on 07/run.py
> +res = np.mean(np.double(q))
`res` лучше переименовать в `accuracy`

2020-11-30 08:28 UTC, merged