05
redpandageddon/mmadpractice pull request #8
Opened 2020-11-22 16:53 UTC by aqaqaqaqaq

2020-11-22 17:04 UTC, redpandageddon requested changes

2020-11-22 17:04 UTC, redpandageddon commented on 05/kNN.py
> +    #        [4, 5]])
Ненужные комментарии

2020-11-22 17:04 UTC, redpandageddon commented on 05/kNN.py
> +    # [1, 4, 9]
Ненужные комментарии

2020-11-22 17:04 UTC, redpandageddon commented on 05/kNN.py
> +    # Индексы строк ближайших соседей были получены на предыдущем шаге.
Ненужные комментарии

2020-11-22 17:04 UTC, redpandageddon commented on 05/kNN.py
> +
Убрать

2020-11-22 17:04 UTC, redpandageddon commented on 05/kNN.py
> +    # TODO: определить наиболее часто встречающийся класс в этом векторе. Просто раскомментируйте код ниже:
Убрать

2020-11-22 17:04 UTC, redpandageddon commented on 05/kNN.py
> +    # no mistake
Убрать

2020-11-22 17:04 UTC, redpandageddon commented on 05/kNN.py
> +    # return ...
Убрать

2020-11-22 17:04 UTC, redpandageddon commented on 05/kNN.py
> +# no mistake
Убрать

2020-11-22 17:04 UTC, redpandageddon commented on 05/run.py
> +# X = np.array(...)
Убрать

2020-11-22 17:04 UTC, redpandageddon commented on 05/run.py
> +# Для преобразования строки к целому числу использовать функцию int()
Убрать

2020-11-22 17:08 UTC, redpandageddon requested changes

2020-11-22 17:08 UTC, redpandageddon commented on 05/kNN.py
> +    return indexOfMin
можно использовать argmin из модуля numpy

2020-11-30 08:31 UTC, stanislavlyalin commented on 05/kNN.py
> +    sub_X=X[:,[0,1]]
Столбцов признаков не обязательно 2. Лучше брать так: `sub_X=X[:, :-1]`

2020-11-30 08:31 UTC, stanislavlyalin commented on 05/kNN.py
> +        distances[i]= float(dist(sub_X[i],obj))
Можно сделать более "питоново":
```python
distances = [dist(item, obj) for item in sub_X]
```

2020-11-30 08:31 UTC, stanislavlyalin commented on 05/kNN.py
> +    distances=np.zeros(sub_X.shape[0])
А где нормализация/стандартизация данных?

2020-11-30 08:31 UTC, stanislavlyalin commented on 05/kNN.py
> +
Строки 9-17 - какая-то магия. Нужно просто получить индексы расстояний `distances`, отсортированные по возрастанию расстояния. Для этого используйте `np.argsort`. Затем нужно взять первые `k` индексов и по ним выбрать классы из последнего столбца `X`. Всё это делается в пару строк кода.

2020-12-07 04:50 UTC, stanislavlyalin requested changes

2020-12-07 04:50 UTC, stanislavlyalin commented on 05/kNN.py
> +        distances = [dist(item, obj) for item in sub_X]
Можно оставить только эту строку. Строки 13 и 14 не нужны.

2020-12-07 04:50 UTC, stanislavlyalin commented on 05/kNN.py
> +    nearest_classes=[X[index[item],2] for item in range(k)]
Можно сделать ещё чуть проще, не используя цикл, если брать значения из `X` так:
```python
nearest_classes = X[index[:k], 2]
```

2020-12-11 17:13 UTC, stanislavlyalin requested changes

2020-12-11 17:13 UTC, stanislavlyalin commented on 05/kNN.py
> +return arr
Что за беда с отступом? В питоне отступы важны.

2020-12-11 17:13 UTC, stanislavlyalin commented on 05/kNN.py
> +        distances = [dist(item, obj) for item in sub_X]
Тут тоже беда с отступом.

2020-12-11 17:13 UTC, stanislavlyalin commented on 05/kNN.py
> +
Зачем столько переносов строк?

2020-12-14 04:40 UTC, merged